dist: trusty
sudo: required
language: node_js
node_js:
- "10"

os:
- linux
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

jobs:
  include:
  - stage: build & publish showcase
    script:
    - npm run build:demo
    deploy:
      provider: pages
      skip_cleanup: true
      github_token: $GITHUB_TOKEN
      local_dir: dist/social-media-showcase
    if: branch = master
