language: node_js
node_js:
- "stable"
jobs:
  include:
  - stage: build & publish showcase
    script:
    - npm run build:demo
    deploy:
      provider: pages
      skip_cleanup: true
      github_token: $GITHUB_TOKEN
      local_dir: dist/social-media-showcase
    if: branch = master
