node_js:
  - "8"
 
branches:
  only:
    - master
 
cache:
  directories:
    - node_modules
 
script:
  - npm run build:demo
 
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/social-media-showcase
  on:
    branch: master

